### ISSUE TITLE
Total proceeds in the input file doesn't match the total proceeds in the 1099.

### ISSUE THREAD

**Issue by uttara-cmu** [JiahaoShan/Glacier-tax-1099-B-Stock-Transactions-Helper#1]
I have formatted this exactly the way you have given in readme. The sum on the proceeds column matches the glacier tax proceeds column, but I get this error

**Comment by JiahaoShan** [comment]
1. Please check your the total proceeds to be the same as the number in your 1099.   
2. If that is correct, you may have a number typo in one or a few transactions (proceeds)

**Comment by uttara-cmu** [comment]
Thanks for responding quickly and this is a very useful extension if only I can get it to work.
This is according to glacier

Total Proceeds (Box 2) 1099-B	151.52	

If I add up the proceeds column in the csv file I get exactly 151.52 which means I cannot have a typo, right? Should the proceeds match some format? 

If not, can you remove this check from the code? It is better to upload in bulk and manually change a few if need be, instead of not being able to upload anything.

**Comment by JiahaoShan** [comment]
Thanks for the response. 
1. Is it possible that you didn't include header line in your csv file?

2. Try open the csv in Excel or Numbers to see if there is any issue with your csv format.

3. Since the extension is working on my side and if you don't mind, you may copy your csv file here and I will check it out for you.

**Comment by uttara-cmu** [comment]
Thanks again. I pasting the first few lines from the csv

name,acquired,sold,proceeds,cost
0.165854 sh. Vanguard Total International Bond ETF Class O,03/09/2016,05/19/2016,9.03,8.96
0.018804 sh. iShares iBoxx $ Investment Grade Cor... Class O,03/09/2016,05/19/2016,2.23,2.17
0.196387 sh. iShares National AMT-Free Muni Bond ETF Class O,03/09/2016,05/19/2016,22.10,21.77

**Comment by JiahaoShan** [comment]
I tracked it down and these lines work for me. The issue may exist in the rest of your transactions. 
By the way, is the third column of your first row in your Stock Transactions table 151.52?

**Comment by uttara-cmu** [comment]
The third column of my first row (non-header row) is the date. If you mean the proceeds, it is 9.03. Should the first column contain the aggregate value? I mean why should it be 151.52? (This is the total proceeds). This is what Glacier is showing me : 
Total Proceeds (Box 2) 1099-B	151.52	Add Transaction

And then it is asking me to add individual stocks which it keeps subtracting from 151.52 (the total amount)

**Comment by JiahaoShan** [comment]
I mean the third column of first row in your Glacier not in your CSV file, which 151.52 is correct. I do appreciate your feedback, but I couldn't find the issue from the information you provided. i think you may help to improve this extension by a pull request if you know JS programming. 

Otherwise, you may simply right click on the Glacier page and click Inspect. Move to Sources tab, click top, click Glacier tax 1099-B... , open inject.js under src/inject and set a breakpoint by clicking on the line 219. Choose file again and see what is going on there. (Based on your name, I assume you come from CMU?)

**Comment by uttara-cmu** [comment]
Ok, just did that. I think this is a floating point rounding error. I get inputTotalProceeds = 151.51999999999995 at line 217 when I set the break point. Can you floor this to two decimal points? I think that will resolve the issue.

Yes! I am from CMU. Unfortunately, I don't know javascript, I am an Information Systems Managemet PhD student  which is more of Econ + Stats. Just know enough to understand what is going on.

**Comment by JiahaoShan** [comment]
Gotcha. Thank you so much for helping me dig the issue! 
CMU is so great, enjoy! Good luck to the rest of your academic studies.

**Comment by uttara-cmu** [comment]
Fantastic. It just started working. Oh, I am so grateful to this software. Was experimenting with stocks and realized how painful it is to do it by hand. I will give you a five star rating :-) Again, thanks a lot!

**Comment by JiahaoShan** [comment]
Thank you!
